language: rust
rust:
  - nightly

notifications:
  slack:
    secure: ubVihNnWNfR8KEvIazHTrrunHJ+QwK4VqYZDbW54AiiRwgsqJz8iZxyncJy6M5eECz3GmaS35bZVuAI0F5SyvVjqelheX/gjj65yOGqs05fNrOltHQue8rz33RTEuDFwAVbEHZWAL+9gWG0cHu+o8bWntT94OIEzfYtqNIJDVonrpLCppy3gnvblUwxlMtMkxbXhN9Wa4O+XaXq04NUdhG/U6bdWjwf1WLcwj49oUFjodGnsXWFnDfTRnaCrjQwAwjsYLaQc3xN0YXa3ci2WvhnhjGWHfCLEyUFM19/g+j8jooZUMbVHgzxPihRK7teRmb4cLPN9eniJl1tDaNnFQCYm88vCHzSpKSMC+wlrzCw3ZzdfvxjB5+Akx6N5bl5TmypwUbSmEdoOdEhjzAeEQA1lFUyMj3z6c/4SWiI2HOjXmZvrCLCVpN8ZzZDzpaFb/c9nwJmxuBKRFs+ClEL5282ThhUTt7HFanXazcpdzHkGUDiVzcl30SL2TNNqL12DRTcxIp9cNmjDqdA3pfRL2pJ0QqGleGFQwcRJQwbWFA7TP4RjNT0Hv+8I2EOhKLhBFyB8ph9VkSuQZLxsqAaAVTXJoffRgSioKM17NSAElzG0OltJqTx3HHqydxurR8sOboGlbySGdLnh7Bhp7X+G+3YctDZ9c7kUeyVbprJkbLc=
