language: rust

notifications:
  slack:
    rooms:
      secure: wZet96SVl28JnBUV0MYLgvVeoDk1enKq+5ao6dfeZT+y8RLUan9DVrQkj3F16IHeZ9aPW2G+rirZCUzFR7WkHDaYwxIAbCTKyXweonCsFSHpqTXNOAECZc9xloeKHbLClGjzmobUPRMzBsjpi7n2ztZcTrl9vkDJjVVWhGBTyPf7ILfW4yCVCXLq9/QRK9QpHkRxN0SbbPTFZQ58QkuD29MrNuQ8kTmKa4XCyyhk+AC0zmltC40DV+iTKNaGw5edWOX1biGD9vkVBQ9NvmvOmSz54gJnOiVGUWQi7MAKnoX478u3vi2pApD4EZ+c6RKXMIsDh9Ilyi8b7z3coPRy1bmmh/0vqB2Gp4iYaQPRan8OePMnIpDG8iryfcK+zp0B26T79qh5FtMtvpi6cmKgW2+rtzeptDcBA+rjd1Q40KuhdP/Ak4XvqLtV9mA18b+sFYy3mv/D+yhJ8H26CnMTHdq1QL0nNqzjIecPQwToBO+c8M2Fq6ndfP9H5E4u+NywUkicGhUZV4HT1eUg4vNEWm7TPCKYE7Ix8/0jmsjxeXYQFmbGKnu1K6hDqEnhe1hRLBWDg7sJlnPZ1fgZF1wZgVT4xikQOuarYT1bTzQRYMJFptdZUTfjyTaSMxRMsvGm5VhAQb3CSKIRyyarU66hDreb47s77LZxw8UU5smpazk=
